Master/urls.py
from django.urls import path
from . import views

app_name = "Master"

urlpatterns = [
   
   #####################ADMIN####################################
   
   path('master/',views.master_page,name="admin_login"),
   path('admin_dashboard/',views.admin_login,name="admin_dashboard"),
   
   ####################User#########################################
   
   path('usermanagement/',views.usermanagement,name="usermanagement"),
   path('adduser/',views.add_user,name="addUser"),
   # path('edituser/<int:id>',views.edit_user,name="editUser"),
   path('deleteuser/<int:id>',views.delete_user,name="deleteUser"),
   
   #####################Movies######################################
   
   path('moviemanagement/',views.moviemanagement,name="moviemanagement"),
   path('moviedetails/<int:id>',views.movie_details,name="moviedetails"),
   path('addmovieform/',views.addmoviesform,name="addmoviesform"),
   path('editmovies/<int:id>',views.edit_movie,name="editmovie"),
   path('deletemovie/<int:id>',views.delete_movie,name="deletemovie"),
   
   ######################series#####################################
   path('seriesmanagement/',views.seriesmanagement,name="seriesManagement"),
   path('seriesdetails/<int:id>',views.series_details,name="seriesdetails"),
   path('addseriesform/',views.addseriesform,name="addseriesform"),
   path('editseries/<int:id>',views.edit_series,name="editseries"),
    path('deleteseries/<int:id>',views.delete_series,name="deleteseries"),
    
    ################Animes###########################################
    path('animemanagement/',views.animemanagement,name="animeManagement"),
    path('animedetails/<int:id>',views.anime_details,name="animedetails"),
    path('addanimeform/',views.add_anime,name="addanimeform"),
    path('editanime/<int:id>',views.edit_anime,name="editanime"),
    path('deleteanime/<int:id>',views.delete_anime,name="deleteanime"),
    
    #################Movie Review################################
    
    path('MovieReview/<int:id>',views.add_Movie_Review,name="movieReview"),
    path('SeriesReview/<int:id>',views.add_series_Review,name="seriesReview"),
    path('AnimeReview/<int:id>',views.add_anime_Review,name="animeReview"),
    
    
    path('editMovieReview/<int:movie_id>/<int:review_id>',views.edit_movie_reviews,name="edit_movie_review"),
    path('deleteMovieReview/<int:movie_id>/<int:review_id>',views. delete_movie_reviews,name="delete_movie_review")
    
]

ReviewPoint/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Accounts.urls")),
    path('',include("Master.urls")),
]

Master/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

###############MOVIES##########################

class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    genre = models.CharField(max_length=100)
    director=models.CharField(max_length=30)
    cast=models.CharField(max_length=300)
    release_date=models.DateField()
    avearge_rating=models.FloatField(default=0)
    image=models.URLField(default = None,null = True)
    
    def __str__(self):
        return self.title
##############################################################

########################SERIES################################
 
class Series(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    genre = models.CharField(max_length=100)
    creators=models.CharField(max_length=30)
    cast=models.CharField(max_length=300)
    avearge_rating=models.FloatField(default=0)
    ONGOING = 'ongoing'
    FINISHED = 'finished'
    STATUS_CHOICES = [
        (ONGOING, 'Ongoing'),
        (FINISHED, 'Finished'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=ONGOING)
    seasons = models.IntegerField()
    episodes = models.IntegerField()
    image=models.URLField(default = None,null = True)
    
    def __str__(self):
        return self.title
    
class Anime(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    genre = models.CharField(max_length=100)
    Author = models.CharField(max_length=50)
    avearge_rating=models.FloatField(default=0)
    ONGOING = 'ongoing'
    FINISHED = 'finished'
    STATUS_CHOICES = [
        (ONGOING, 'Ongoing'),
        (FINISHED, 'Finished'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=ONGOING)
    episodes = models.IntegerField()
    image=models.URLField(default = None,null = True)
    
    def __str__(self):
        return self.title
    
    
class MovieReview(models.Model):
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField(max_length = 1000)
    rating = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.username 
    
class SeriesReview(models.Model):
    series = models.ForeignKey(Series,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField(max_length = 1000)
    rating = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.username 
    
class AnimeReview(models.Model):
    anime = models.ForeignKey(Anime,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField(max_length = 1000)
    rating = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.username 

Master/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class Movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ("title","description","genre","director","cast","release_date","image")
        
class AddUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","email")
        
class Seriesform(forms.ModelForm):
    class Meta:
        model = Series
        fields = ("title","description","genre","creators","cast","status","seasons","episodes","image")


class Animeform(forms.ModelForm):
    class Meta:
        model = Anime
        fields = ("title","description","genre","Author","status","episodes","image")
        
class MovieReviewform(forms.ModelForm):
    class Meta:
        model = MovieReview
        fields=("comment","rating")  
        
class seriesReviewform(forms.ModelForm):
    class Meta:
        model = SeriesReview
        fields=("comment","rating")  
        
class AnimeReviewform(forms.ModelForm):
    class Meta:
        model = AnimeReview
        fields=("comment","rating") 

Master/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from .models import *
from .forms import *
from django.db.models import Avg
# Create your views here.

###################ADMIN###########################

##############ADMIN LOGIN PAGE############

def master_page(request):
    request.session.clear()
    return render(request,"admin_login.html")

############# Admin DASHBOARD##############

def admin_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(password)

        user = User.objects.get(username=username)
        if user.is_superuser:
            if password == "0471":
                return render (request,"admin_dashboard.html")
            else :
                return redirect('admin_login')
        else :
            return redirect('home')
    return redirect('home')

####################USERS#########################

###########User Management#############
def usermanagement(request):
    users = User.objects.all()
    return render(request,"usermanage.html",{"users" : users})  

###################ADD USER#################
def add_user(request):
    if request.method == "POST":
        form = AddUserForm(request.POST) 
        
        if form.is_valid():
            user = form.save()
            user.save()
            return redirect('Master:usermanagement')
    else :
        form = AddUserForm()
        return render(request,"addform.html",{"form":form})  
    
# def edit_user(request,id):
#     user = User.objects.get(id=id)
#     if request.method == "POST":
#         form = AddUserForm(request.POST or None)
#         if form.is_valid():
#             data=form.save(commit=False)
#             data.save()
#             return redirect("Master:usermanagement",id)
#     else :
#         form = AddUserForm(instance=user)
#     return render(request,'addUser.html',{"form":form})
    
#################EDIT USER##############
def delete_user(request,id):
    if request.method == "GET":
        user = User.objects.get(id=id)
        user.delete()
        return redirect('Master:usermanagement')   
    return redirect('Master:usermanagement')  

############MOVIES##################################

###############MOVIE MANAGEMENT##############

def moviemanagement(request):
    
    allmovies = Movie.objects.all()
    context = {
        "movies" : allmovies
    } 
    return render(request,"shows.html",context)     

#################MOVIE DETAILS PAGE#################

def movie_details(request,id):
    user = User.objects.all()
    movie = Movie.objects.get(id=id)
    reviews = MovieReview.objects.filter(movie=id).order_by("comment")
    average = reviews.aggregate(Avg("rating"))['rating__avg']
    if average ==None :
        average = 0 
    average=round(average,2)
    if user :
        username = request.session.get('username', None)
    context = {
        "movie" : movie,
        "data": username,
        "reviews" : reviews,
        "average" : average,
    }
    
    return render (request,"details.html",context)

#####################ADDING MOVIES###################
def addmoviesform(request):
    if request.method == "POST":
        form = Movieform(request.POST or None)
        if form.is_valid():
            data=form.save(commit=False)
            data.save()
            return redirect('Master:moviemanagement')
        print("form.errors")
    else :
        form =Movieform()
        return render(request,"addform.html",{"form": form,"caption":"Add Movies"})

####################EDIT MOVIES#####################

def edit_movie(request,id):
    movie = Movie.objects.get(id=id)
    if request.method == "POST" :
        form = Movieform(request.POST or None,instance=movie)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("Master:moviedetails",id)
    else :
        form = Movieform(instance=movie)
    return render(request,"addform.html",{"form":form,"caption":"Edit Movies"})
    
###############DELETE MOVIES###################

def delete_movie(request,id):
    if request.method == "GET" :
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('Master:moviemanagement')
    
###################WEB SERIES#####################

#####################SERIES MANAGEMENT###################    

def seriesmanagement(request):
    
    allseries = Series.objects.all()
    context = {
        "series" : allseries
    } 
    return render(request,"shows.html",context)  

#############SERIES DETAILS PAGE#################

def series_details(request,id):
    user = User.objects.all()
    reviews = SeriesReview.objects.filter(series=id).order_by("comment")
    if user :
        username = request.session.get('username', None)
    series = Series.objects.get(id=id)
    context = {
        "series" : series,
        "data": username,
        "reviews" : reviews,
    }
    
    return render (request,"details.html",context)

#################SERIES ADDING PAGE######################

def addseriesform(request):
    if request.method == "POST":
        form = Seriesform(request.POST or None)
        if form.is_valid():
            data=form.save(commit=False)
            data.save()
            return redirect('Master:seriesManagement')
        print("form.errors")
    else :
        form =Seriesform()
        return render(request,"addform.html",{"form": form,"caption":"Add Series"})
    
#####################SERIES EDITING###################
    
def edit_series(request,id):
    series = Series.objects.get(id=id)
    if request.method == "POST" :
        form = Seriesform(request.POST or None,instance=series)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("Master:seriesdetails",id)
    else :
        form = Seriesform(instance=series)
    return render(request,"addform.html",{"form":form,"caption":"Edit Series"})
    
###############DELETING SERIES###################

def delete_series(request,id):
    if request.method == "GET" :
        series = Series.objects.get(id=id)
        series.delete()
        return redirect('Master:seriesManagement')
    
###############################################################

#################Anime####################################

def animemanagement(request):
    
    allanime = Anime.objects.all()
    context = {
        "animes" : allanime
    } 
    return render(request,"shows.html",context)  

#############Anime DETAILS PAGE#################

def anime_details(request,id):
    user = User.objects.all()
    reviews = AnimeReview.objects.filter(anime=id).order_by("comment")
    if user :
        username = request.session.get('username', None)
    anime = Anime.objects.get(id=id)
    context = {
        "animes" : anime,
        "data": username,
        "reviews" : reviews,
    }
    return render (request,"details.html",context)

######################Add anime##########################

def add_anime(request):
    if request.method == "POST":
        form = Animeform(request.POST or None)
        if form.is_valid():
            data=form.save(commit=False)
            data.save()
            return redirect('Master:animeManagement')
        print("form.errors")
    else :
        form =Animeform()
        return render(request,"addform.html",{"form": form,"caption":"Add Anime"})
    
####################Edit Anime########################

def edit_anime(request,id):
    anime = Anime.objects.get(id=id)
    if request.method=="POST":
        form = Animeform(request.POST or None ,instance=anime)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("Master:animedetails",id)
    else :
        form = Animeform(instance=anime)
        return render(request,"addform.html",{"form":form,"caption":"Edit Anime"})
        
#################Delete Anime###############################

def delete_anime(request,id):
    if request.method =="GET":
        anime = Anime.objects.get(id=id)
        anime.delete()
        return redirect("Master:animeManagement")
    
####################REVIEW####################################

#####################ADD REVIEW###########################
def add_Movie_Review(request,id):
    movie = Movie.objects.get(id=id)
    if request.method == "POST":
        form = MovieReviewform(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.comment = request.POST["comment"]
            data.rating = request.POST["rating"]
            data.user = request.user
            data.movie = movie
            data.save()
            return redirect("Master:moviedetails",id)
        else:
            form = MovieReviewform
        return render(request,"details.html",{"form":form})
    
def add_series_Review(request,id):
    series = Series.objects.get(id=id)
    if request.method == "POST":
        form = seriesReviewform(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.comment = request.POST["comment"]
            data.rating = request.POST["rating"]
            data.user = request.user
            data.series = series
            data.save()
            return redirect("Master:seriesdetails",id)
        else:
            form = seriesReviewform
        return render(request,"details.html",{"form":form})
    
def add_anime_Review(request,id):
    anime = Anime.objects.get(id=id)
    if request.method == "POST":
        form = AnimeReviewform(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.comment = request.POST["comment"]
            data.rating = request.POST["rating"]
            data.user = request.user

Master/templates/addUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Form</title>
</head>
<body>
    <h2>Add Movie</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

Master/templates/addform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Form</title>
</head>
<style>
    .form-dv{
        display: flex;
        flex-direction: column;
        text-align: center;
    }
</style>
<body>
    <div class="form-dv">
    <h2>{{caption}}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    </div>
</body>
</html>

Master/templates/addmovies.html
<!-- templates/movie_form.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Form</title>
</head>
<body>
    <h2>Add Movie</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

Master/templates/admin_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/admin_dashboard.css' %}">
</head>
<body>
    {% include 'header.html' %}
    <div class="cards">
        <a href="{% url 'Master:usermanagement' %}"><button>User <br>Management</button></a>
        <a href="{% url 'Master:moviemanagement' %}"><button>Movies <br> Management</button></a>
        <a href="{% url 'Master:seriesManagement' %}"><button>Web Series <br> Management</button></a>
        <a href="{% url 'Master:animeManagement' %}"><button>Anime <br> Management</button></a>
    </div>
</body>
</html>

Master/templates/admin_login.html
{% load static %}
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>Glowing Inputs Login Form UI</title>
      <link rel="stylesheet" href="style.css">
      <link rel="stylesheet" href="{% static 'css/admin_login.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
   </head>
   <body>
      <div class="login-form">
         <div class="text">
            LOGIN
         </div>
         <form action="{% url 'Master:admin_dashboard' %}" method="post">
            {% csrf_token %}
            <div class="field">
               <!-- <div class="fas fa-envelope"></div> -->
               <input type="text" placeholder="Admin Name" name="username">
            </div>
            <div class="field">
               <!-- <div class="fas fa-lock"></div> -->
               <input type="password" placeholder="Password" name="password">
            </div>
            <button type="submit">Submit</button>
         </form>
      </div>
   </body>
</html>

Master/templates/details.html
{% load static %}
{% include 'header.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <title>Document</title>
</head>
<html>
    {% if movie %}
    <div class="container">   
        <div class="img">
            <img src="{{movie.image}}" alt="{{movie.name}}">
        </div>
        <div class="about">
            <h3 style="font-size: 50px;">{{movie.title}}</h3>
            <p style="font-size: 20px; color:black">{{movie.description}}</p>
            <h5 style="font-size: 22px;">Director - {{movie.director}}</h5>
            <h5 style="font-size: 22px;">Cast - {{movie.cast}}</h5>
            <h5>Average - {{average}}/10</h5>
            {% if data %}
                {{pass}}
            {% else %}
                <a href="{% url 'Master:editmovie' movie.id %}"><button>Edit Movie</button></a>
                <a href="{% url 'Master:deletemovie' movie.id %}"><button onclick="return confirm('Are you sure you want to delete this movie')">Delete Movie</button></a>
            {% endif %}
        </div>
    </div>
    <div class="review">
            <form action="{% url 'Master:movieReview' movie.id %}" method="post">
                {% csrf_token %}
            <div class="moviereview">
                <label for="MovieReview">Add Review</label>
                <textarea name="comment" id="" cols="30" rows="5"></textarea>
            </div>
            <div class="rating">
                <label for="Rating" style="margin-bottom: 20px;">Add Rating</label>
                <input type="integer" name="rating" class="rating-inp">
                <input type="submit" class="rating-btn">
            </div>
        </form>
    </div>
    <div class="reviewlist">
        <h1 style="text-align: center;">REVIEWS</h1>
        <div class="review-card">
        {% for review in reviews %}
            <div class="reviews">
            <p style="font-size: 25px; color: black;margin-bottom:5px">{{review.comment}}</p>
            <p style="font-size: 15px; color:rgba(0, 0, 0, 0.548)" class="post-p">Posted by - {{review.user}}</p>
            <p style="font-size: 20px; color: black;margin-bottom:5px">rating - {{review.rating}}</p>
            {% if request.user == review.user %}
            <a href="{% url 'Master:edit_movie_review' movie.id review.id %}">Edit</a>
            <a href="{% url 'Master:delete_movie_review' movie.id review.id %}" onclick="return confirm('are you sure you want to delete this comment')">Delete</a>
            {% endif %}
            {% if data %}
            {{pass}}
            {% else %}
            <a href="{% url 'Master:delete_movie_review' movie.id review.id %}" onclick="return confirm('are you sure you want to delete this comment')">Delete</a>
            {% endif %}
            </div>
        {% endfor %}
    </div>
    </div>
    {% endif %}   
    {% if series %}
        <div class="container">
            <div class="img">
                <img src="{{series.image}}" alt="{{movie.name}}">
            </div>
            <div class="about">
                <h3 style="font-size: 50px;">{{series.title}}</h3>
                <p style="font-size: 20px; color:black">{{series.description}}</p>
                <h5 style="font-size: 22px;">Creators  - {{series.creators}}</h5>
                <h5 style="font-size: 22px;">Cast - {{series.cast}}</h5>
                <h5 style="font-size: 22px;">Status - {{series.status}}</h5>
                <h5 style="font-size: 22px;">No.of.Seasons - {{series.seasons}}</h5>
                <h5 style="font-size: 22px;">No.of episodes - {{series.episodes}}</h5>
                {% if data %}
                    {{pass}}
                {% else %}
                <a href="{% url 'Master:editseries' series.id %}"><button>Edit Series</button></a>
                <a href="{% url 'Master:deleteseries' series.id %}"><button onclick="return confirm('Are you sure you want to delete this web series')">Delete Series</button></a>
                {% endif %}
            </div>
        </div>
        <div class="review">
                <form action="{% url 'Master:seriesReview' series.id %}" method="post">
                    {% csrf_token %}
                <div class="moviereview">
                    <label for="MovieReview">Add Review</label>
                    <textarea name="comment" id="" cols="30" rows="5"></textarea>
                </div>
                <div class="rating">
                    <label for="Rating" style="margin-bottom: 20px;">Add Rating</label>
                    <input type="number" name="rating" class="rating-inp">
                    <input type="submit" class="rating-btn">
                </div>
            </form>
        </div>
        <div class="reviewlist">
            <h1 style="text-align: center;">REVIEWS</h1>
            {% for review in reviews %}
                <div class="reviews">
                <p style="font-size: 40px; color: black;margin-bottom:10px">{{review.comment}}</p>
                <p style="font-size: 15px; color:rgba(0, 0, 0, 0.548)">Posted by - {{review.user}}</p>
                <p></p>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        {% if animes %}
            <div class="container">
                <div class="img">
                    <img src="{{animes.image}}" alt="{{animes.name}}">
                </div>
            <div class="about">
                <h3 style="font-size: 50px;">{{animes.title}}</h3>
                <p style="font-size: 20px; color:black">{{animes.description}}</p>
                <h5 style="font-size: 22px;">author  - {{animes.Author}}</h5>
                <!-- <h5 style="font-size: 22px;">Cast - {{series.cast}}</h5> -->
                <h5 style="font-size: 22px;">Status - {{animes.status}}</h5>
                <!-- <h5 style="font-size: 22px;">No.of.Seasons - {{series.seasons}}</h5> -->
                <h5 style="font-size: 22px;">No.of episodes - {{animes.episodes}}</h5>
                {% if data %}
                    {{pass}}
                {% else %}
                <a href="{% url 'Master:editanime' animes.id %}"><button>Edit anime</button></a>
                <a href="{% url 'Master:deleteanime' animes.id %}"><button onclick="return confirm('Are you sure you want to delete this anime')">Delete anime</button></a>
                {% endif %}
                </div>
            </div>
            <div class="review">
                <form action="{% url 'Master:animeReview' animes.id %}" method="post">
                    {% csrf_token %}
                <div class="moviereview">
                    <label for="MovieReview">Add Review</label>
                    <textarea name="comment" id="" cols="30" rows="5"></textarea>
                </div>
                <div class="rating">
                    <label for="Rating" style="margin-bottom: 20px;">Add Rating</label>
                    <input type="number" name="rating" class="rating-inp">
                    <input type="submit" class="rating-btn">
                </div>
            </form>
        </div>
        <div class="reviewlist">
            <h1 style="text-align: center;">REVIEWS</h1>
            {% for review in reviews %}
                <div class="reviews">
                <p style="font-size: 40px; color: black;margin-bottom:10px">{{review.comment}}</p>
                <p style="font-size: 15px; color:rgba(0, 0, 0, 0.548)">Posted by - {{review.user}}</p>
                </div>
            {% endfor %}
        </div>
        {% endif %}
            
        </html>
    </body>
    </html>

Master/templates/editreview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if movies %}
    <div class="card-content">
        <h3 class="text-center">Edit Review</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            {% if error %}
                <strong style="color: red;">{{error}}</strong>
            {% endif %}
            <input type="submit" value="Save changes" class="btn btn-danger">
        </form>
    </div>
    {% endif %}
</body>
</html>

Master/templates/movies.html
{% load static %}
{% include 'header.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/movies.css' %}">
</head>
<body>
    
    <div class="movie-container">
        {% for movie in movies %}
            <div class="movie-card">
                <a href="{% url 'Master:moviedetails' movie.id %}"><img src="{{ movie.image }}" alt="{{ movie.title }}"></a>
                <div class="movie-info">
                    <h2>{{ movie.title }}</h2>
                    <p>{{ movie.release_date }}</p>
                </div>
            </div>
        {% endfor %}
</body>
</html>

Master/templates/usermanage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/usermanage.css' %}">

    <style>
        button{
            cursor: pointer;
            color: white;
        }
        
    </style>

</head>
<body>
    {% include 'header.html' %}
    <div class="usertable">
    <h1>User Table</h1>
    <table border= "1">
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                {% comment %} <!-- <th>Edit User</th> --> {% endcomment %}
                <th>Delete User</th>
                <!-- <th>Password</th> -->
                <!-- Add more columns for additional user class details -->
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td style="color: beige;">{{user.username}}</td>
                    <!-- {% comment %} <td><a href="{% url 'edituser' user.id %}">{{ user.username }}</a></td> {% endcomment %} -->
                    <td>{{ user.email }}</td>
                    {% comment %} <!-- <td><a href="{% url 'Master:editUser' user.id %}" style="color: skyblue;">Edit</a></td> --> {% endcomment %}
                    <td><a href="{% url 'Master:deleteUser' user.id %}" style="color: red;">Delete</a></td>
                    <!-- <td><a href=""></a>{{ user.password }}</td> -->
                    <!-- Add more cells for additional user class details -->
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% comment %} <!-- <button><a href="{% url 'addUserpage' %}">Add User</a></button> --> {% endcomment %}
    {% comment %} <a href="{% url 'addUserpage' %}"><button>Add User</button></a> {% endcomment %}
</div>
</body>
</html>