Accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.home,name='home'),
   path('register/',views.Register_user,name='register'),
   path('login/',views.login_user,name="login"),
   path('landingpage/',views.land,name="land"),
    path('logout/',views.logout_user,name="logout"),
    path('movielist/',views.movielist,name="movielist"),
    path('serieslist/',views.series_list,name="serieslist"),
     path('animelist/',views.anime_list,name="animelist"),
]

Master/urls.py
from django.urls import path
from . import views

app_name = "Master"

urlpatterns = [
   
   #####################ADMIN####################################
   
   path('master/',views.master_page,name="admin_login"),
   path('admin_dashboard/',views.admin_login,name="admin_dashboard"),
   
   ####################User#########################################
   
   path('usermanagement/',views.usermanagement,name="usermanagement"),
   path('adduser/',views.add_user,name="addUser"),
   # path('edituser/<int:id>',views.edit_user,name="editUser"),
   path('deleteuser/<int:id>',views.delete_user,name="deleteUser"),
   
   #####################Movies######################################
   
   path('moviemanagement/',views.moviemanagement,name="moviemanagement"),
   path('moviedetails/<int:id>',views.movie_details,name="moviedetails"),
   path('addmovieform/',views.addmoviesform,name="addmoviesform"),
   path('editmovies/<int:id>',views.edit_movie,name="editmovie"),
   path('deletemovie/<int:id>',views.delete_movie,name="deletemovie"),
   
   ######################series#####################################
   path('seriesmanagement/',views.seriesmanagement,name="seriesManagement"),
   path('seriesdetails/<int:id>',views.series_details,name="seriesdetails"),
   path('addseriesform/',views.addseriesform,name="addseriesform"),
   path('editseries/<int:id>',views.edit_series,name="editseries"),
    path('deleteseries/<int:id>',views.delete_series,name="deleteseries"),
    
    ################Animes###########################################
    path('animemanagement/',views.animemanagement,name="animeManagement"),
    path('animedetails/<int:id>',views.anime_details,name="animedetails"),
    path('addanimeform/',views.add_anime,name="addanimeform"),
    path('editanime/<int:id>',views.edit_anime,name="editanime"),
    path('deleteanime/<int:id>',views.delete_anime,name="deleteanime"),
    
    #################Movie Review################################
    
    path('MovieReview/<int:id>',views.add_Movie_Review,name="movieReview"),
    path('SeriesReview/<int:id>',views.add_series_Review,name="seriesReview"),
    path('AnimeReview/<int:id>',views.add_anime_Review,name="animeReview"),
    
    
    path('editMovieReview/<int:movie_id>/<int:review_id>',views.edit_movie_reviews,name="edit_movie_review"),
    path('deleteMovieReview/<int:movie_id>/<int:review_id>',views. delete_movie_reviews,name="delete_movie_review")
    
]

ReviewPoint/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Accounts.urls")),
    path('',include("Master.urls")),
]

Accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","password")

Accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from Master.models import *
from django.contrib.auth import authenticate,login,logout
from django.views.decorators.csrf import csrf_protect
from .forms import *

# Create your views here.

##################HOME PAGE####################
def home(request):
    return render(request,"home.html")

#####################USER REGISTRATION###############

def Register_user(request):
    if request.method == "POST" :
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        if not User.objects.filter(username=username).exists():
            user = User(username=username, email=email)
            user.set_password(password)
            user.save()

            
            return redirect('home')
        else :
             response=f"""
            <script>
            window.alert("User already Exists")
            window.location.href='/';
            </script>
            """
             return HttpResponse(response)
    return redirect('home')
    
   

#######################USER LOGIN#######################

def login_user(request):
    # if request.method == "GET":
    #     return render(request,"home.html")
    if request.method == "POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        
        user=authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                request.session['username'] = username
                return render(request,"landing_page.html",{"data":username})
            else:
                response = f"""
                <script>
                window.alert('WRONG PASSWORD')
                window.location.href ='/';
                </script>
                """
                return HttpResponse(response)
        else:
            response = f"""
            <script>
            window.alert('No User Found')
            window.location.href ='/';
            </script>
            """
            return HttpResponse(response)
        
        
def land(request):
    username = request.session['username']
    return render(request,"landing_page.html",{"data":username})


###################USER LOGOUT######################

def logout_user(request):
    request.session.clear()
    return redirect("/")

###################MOVIES LIST####################

def movielist(request):
    username = request.session.get('username', None)
    allmovies = Movie.objects.all()
    context = {
        "movies": allmovies,
        "data": username,
    } 
    return render(request,"shows.html",context)

#######################SERIES LIST####################

def series_list(request):
    username = request.session.get('username', None)
    allseries = Series.objects.all()
    context = {
        "series" : allseries,
        "data" : username,
    }
    return render(request,"shows.html",context)

def anime_list(request):
    username = request.session.get('username', None)
    allanime = Anime.objects.all()
    context = {
        "animes" : allanime,
        "data" : username,
    }
    return render(request,"shows.html",context)
    

Accounts/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
</head>
<body>
    <div class="header">
        <div class="logo">
            <h1><a href="{% url 'land' %}">Review Point</a></h1>
            {% if data %}
                {{pass}}
            {% elif users %}
            <a href="{% url 'Master:addUser' %}"><button>Add User</button></a>
            {% elif movies %}
            <a href="{% url 'Master:addmoviesform' %}"><button>Add movies</button></a>
            {% elif series %}
            <a href="{% url 'Master:addseriesform' %}"><button>Add Series</button></a>
            {% elif animes %}
            <a href="{% url 'Master:addanimeform' %}"><button>Add Anime</button></a>
            {% endif %}
        </div>
       {% if movies %}
        <div class="search">
            <form action="">
            <input type="search" placeholder="search movies"  class="search-inp">
            <input type="button" value="Search" class="search-btn">
            </form>
        </div>
        {% endif %}
        {% if series %}
        <div class="search">
            <form action="">
            <input type="search" placeholder="search series"  class="search-inp">
            <input type="button" value="Search" class="search-btn">
            </form>
        </div>
        {% endif %}
        {% if animes %}
        <div class="search">
            <form action="">
            <input type="search" placeholder="search anime" class="search-inp">
            <button type="submit" class="search-btn">Search</button>
            </form>
        </div>
        {% endif %}
        <div class="fields">
            <p>Unlimited Shows</p>
            {% if data %}
            <button class="my-account"><a href="" class="profile">{{data}}</a></button>
            {% else %}
            <button class="my-account"><a href="" class="profile">My Account</a></button>
            {% endif %}
            <button class="logout-btn"><a href="{% url 'logout' %}" class="logout">logout</a></button>
            
           
        </div>
    </div>
    
</body>
</html>

Accounts/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <img class="main-img" src="../static/images/shridhar-thorat-RQ1X0LPWuk8-unsplash.jpg" alt="">
   <div class="main-container">
    <div class="about">
        <h1><img src="../static/images/reviewpoint-logo.png" alt="" class="head-img"></h1>
        <p>"Join <span>Review Point</span> your hub for movie, anime, and web series reviews. 
            Dive into discussions, discover hidden gems, and connect with fellow enthusiasts.
             Sign up now and be part of the ultimate entertainment community!"</p>
    </div>
    <div class="box">
        <div class="box1">
            <div class="main">  	
                <input type="checkbox" id="chk" aria-hidden="true">
                    <div class="signup">
                        <form action="{% url 'register' %}" method="post">
                            {% csrf_token %}
                            <label for="chk" aria-hidden="true">Sign up</label>
                            <input type="text" name="username" placeholder="Username" required="">
                            <input type="email" name="email" placeholder="email" required="">
                            <input type="password" name="password" placeholder="password" required="">
                            <button>Sign up</button>
                        </form>
                    </div>
        
                    <div class="login">
                        <form action="{% url 'login' %}" method="post">
                            {% csrf_token %}
                            <label for="chk" aria-hidden="true">Login</label>
                            <input type="text" name="username" placeholder="username" required="">
                            <input type="password" name="password" placeholder="Password" required="">
                            <button>Login</button>
                        </form>
                    </div>
            </div>
        </body>
        </html>
        </div>
    </div>
   </div>
</body>
</html>

Accounts/templates/landing_page.html
{% load static %} 
{% include 'header.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/landing_page.css' %}">
</head>
<body>
    {% csrf_token %}

   <!-- <img src="../static/images/background.jpg" alt="" class="background-image"> -->
    <div class="main-container">
        {% comment %} <div class="search">
            <form action="" method="post">
                {% csrf_token %}
                <input type="search" placeholder="Search Shows By Name" class="search-inp">
                <input type="submit" placeholder="Search" class="search-btn">
            </form>    {% endcomment %}
        </div>
        <div class="movie-head">
            <h1>Movies</h1>
        </div>
        <div class="web-head">
            <h1>Web Series</h1>
        </div>
        <div class="ani-head">
            <h1>Animes</h1>
        </div>
        <div class="types">
            <a href="{% url 'movielist' %}" onclick="window.location.href=this.href; return false;"><div class="movies">
               
                <img src="{% static 'images/movie-posters.jpg' %}" alt="">
            </div></a>
            <a href="{% url 'serieslist' %}"><div class="movies">
              
                <img src="{% static 'images/web-posters-new.jpg' %}" alt="">
                </div></a>
            <a href="{% url 'animelist' %}"><div class="movies">
              
                <img src="{% static 'images/anime-poster.jpg' %}" alt="">
                
            </div></a>
        </div>
    </div>
</body>
</html>